controllers:
    resource: ../src/Controller/
    type: attribute

index: 
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::numberAction

